'use client';
import React,{useState} from 'react';
import { motion } from 'framer-motion';
import { Shield, Cable, Wifi, Server, PhoneCall, Mail, MapPin, CheckCircle2, Quote } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import Image from 'next/image';
import logo from './assets/3.png';
const services=[{icon:<Server className='h-8 w-8' aria-hidden/>,title:'Computer Networking',desc:'Switching, routing, VLANs, Wi‑Fi design, and performance tuning for retail, office, and industrial sites.',bullets:['UDM/UDR/UXG deployments','PoE switching & UPS design','VLAN & QoS hardening']},{icon:<Cable className='h-8 w-8' aria-hidden/>,title:'Low‑Voltage Cabling',desc:'Clean, labeled CAT6/CAT6A runs, fiber, racks, patching, and certification with pro documentation.',bullets:['CAT6/CAT6A, fiber, coax','IDF/MDF buildouts','Fluke/LinkRunner testing']},{icon:<Shield className='h-8 w-8' aria-hidden/>,title:'Security Cameras',desc:'Design and deploy Unifi Protect and other IP‑CCTV systems with crisp coverage and reliable retention.',bullets:['4K coverage planning','NVR sizing & storage','Remote monitoring']},{icon:<Wifi className='h-8 w-8' aria-hidden/>,title:'Paging & Audio',desc:'Clear overhead paging and background music with zoning, amps, and clean terminations.',bullets:['70V/24V systems','Zone design','Rack integration']}];
const stats=[{label:'Years Combined Field Experience',value:'15+'},{label:'States Served',value:'20+'},{label:'Average Project CSAT',value:'4.9/5'},{label:'Cameras Deployed',value:'3,000+'}];
export default function RuvisonLanding() {
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setNotice('Quote form submitted (demo mode) — email sending is temporarily disabled.');
    (e.target as HTMLFormElement).reset();
  }
return (<div className='min-h-screen bg-white text-slate-800'>
<header className='sticky top-0 z-40 backdrop-blur bg-white/80 border-b border-slate-200'><div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 flex items-center justify-between h-16'><div className='flex items-center gap-3'><Image src={logo} alt='Ruvison Technologies Logo' width={48} height={48} className='rounded-md'/><span className='font-semibold tracking-tight text-slate-900'>Ruvison Technologies LLC</span></div><nav className='hidden md:flex items-center gap-6 text-sm'><a href='#services' className='hover:text-slate-900'>Services</a><a href='#work' className='hover:text-slate-900'>Work</a><a href='#about' className='hover:text-slate-900'>About</a><a href='#quote' className='hover:text-slate-900'>Request a Quote</a></nav><div className='hidden md:block'><Button asChild><a href='#quote'>Get a Quote</a></Button></div></div></header>
<section className='relative overflow-hidden'><div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-20'><div className='grid lg:grid-cols-2 gap-10 items-center'><div><motion.h1 initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{duration:0.5}} className='text-4xl md:text-5xl font-extrabold tracking-tight'>Reliable Networks & Trusted Security</motion.h1><p className='mt-4 text-lg text-slate-600'>We design, install, and maintain robust low‑voltage infrastructure for retail, commercial, and industrial clients—on time, on spec, and across the U.S.</p><div className='mt-6 flex flex-wrap gap-3'><Button asChild><a href='#quote'>Request a Quote</a></Button><Button variant='outline' asChild><a href='#work'>See Our Work</a></Button></div><div className='mt-6 grid grid-cols-2 sm:grid-cols-4 gap-4'>{stats.map((s)=>(<Card key={s.label} className='rounded-2xl'><CardContent className='p-4'><div className='text-2xl font-bold'>{s.value}</div><div className='text-xs text-slate-500'>{s.label}</div></CardContent></Card>))}</div></div><div><div className='aspect-video rounded-2xl bg-gradient-to-br from-zinc-900 to-zinc-700 shadow-xl grid place-content-center text-white'><div className='text-center p-6'><p className='text-sm uppercase tracking-wider text-white/70'>Featured Build</p><h3 className='text-2xl font-semibold mt-1'>Multi‑site Retail IP‑CCTV & Wi‑Fi Refresh</h3><p className='mt-3 text-white/80 text-sm'>48‑port PoE core, UDM‑SE, UNVR, 4K turrets, fiber uplinks, labeled patching. Delivered ahead of schedule.</p></div></div></div></div></div></section>
<section id='services' className='bg-slate-50 py-20'><div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8'><div className='max-w-2xl'><h2 className='text-3xl font-bold tracking-tight'>What we do</h2><p className='mt-2 text-slate-600'>End‑to‑end projects or white‑label support for primes and MSPs.</p></div><div className='mt-10 grid md:grid-cols-2 lg:grid-cols-4 gap-6'>{services.map((s)=>(<Card key={s.title} className='rounded-2xl'><CardHeader><div className='h-10 w-10 rounded-xl bg-slate-100 grid place-content-center mb-2'>{s.icon}</div><CardTitle className='text-lg'>{s.title}</CardTitle></CardHeader><CardContent><p className='text-sm text-slate-600'>{s.desc}</p><ul className='mt-4 space-y-2 text-sm'>{s.bullets.map((b)=>(<li key={b} className='flex items-start gap-2'><CheckCircle2 className='h-4 w-4 mt-0.5' aria-hidden/>{b}</li>))}</ul></CardContent></Card>))}</div></div></section>
<section id='about' className='bg-slate-50 py-20'><div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-10 items-center'><div><h2 className='text-3xl font-bold tracking-tight'>Why clients choose Ruvison</h2><p className='mt-3 text-slate-600'>We’re detail‑obsessed installers who respect your schedule and budget. From lift logistics to label conventions, we think through what actually keeps field work moving.</p><div className='mt-6 grid md:grid-cols-2 gap-4'>{[{title:'National coverage',text:'Coast‑to‑coast capabilities with vetted crews.'},{title:'Prime‑friendly',text:'White‑label execution and tidy documentation.'},{title:'Safety first',text:'Lift‑certified techs and OSHA‑aware practices.'},{title:'Pro tooling',text:'Fluke, LinkRunner, labelers, and photo checklists.'}].map((item)=>(<Card key={item.title} className='rounded-2xl'><CardContent className='p-5'><div className='font-semibold'>{item.title}</div><div className='text-sm text-slate-600 mt-1'>{item.text}</div></CardContent></Card>))}</div></div><div><Card className='rounded-2xl'><CardHeader><CardTitle className='flex items-center gap-2'><Quote className='h-5 w-5'/>Testimonials</CardTitle></CardHeader><CardContent className='space-y-4'><Testimonial name='Retail Program Manager' text='Ruvison handled our camera refresh with zero drama and detailed photos. Stores were thrilled.'/><Testimonial name='General Contractor' text='On time, professional, and neat. Their documentation made our closeout a breeze.'/><Testimonial name='MSP Lead' text='They think like operators. Smart questions up front saved us change orders later.'/></CardContent></Card></div></div></section>
<section id='quote' className='py-20'><div className='mx-auto max-w-5xl px-4 sm:px-6 lg:px-8'><div className='max-w-2xl'><h2 className='text-3xl font-bold tracking-tight'>Request a Quote</h2><p className='mt-2 text-slate-600'>Tell us about your site(s) and timeline. We’ll follow up within one business day.</p></div><Card className='mt-8 rounded-2xl'><CardContent className='p-6'>{success && <div className='mb-4 rounded-xl border border-green-300 bg-green-50 p-3 text-sm text-green-800'>{success}</div>}{error && <div className='mb-4 rounded-xl border border-red-300 bg-red-50 p-3 text-sm text-red-800'>{error}</div>}<form className='grid md:grid-cols-2 gap-4' onSubmit={onSubmit}><div className='md:col-span-1'><label className='text-sm font-medium'>Name</label><Input name='name' placeholder='Your name' required/></div><div className='md:col-span-1'><label className='text-sm font-medium'>Company</label><Input name='company' placeholder='Company or project'/></div><div className='md:col-span-1'><label className='text-sm font-medium'>Email</label><Input name='email' type='email' placeholder='you@company.com' required/></div><div className='md:col-span-1'><label className='text-sm font-medium'>Phone</label><Input name='phone' type='tel' placeholder='(555) 555‑5555'/></div><div className='md:col-span-2'><label className='text-sm font-medium'>What do you need?</label><div className='grid sm:grid-cols-2 gap-2 mt-2'>{['Computer Networking','Low‑Voltage Cabling','Security Cameras','Paging & Audio','Service Call / Smart Hands','Other'].map((opt)=>(<label key={opt} className='flex items-center gap-2 rounded-xl border p-3 text-sm'><input type='checkbox' name='needs' value={opt} className='h-4 w-4'/> {opt}</label>))}</div></div><div className='md:col-span-2'><label className='text-sm font-medium'>Project details</label><Textarea name='details' placeholder='Sites, scope, timelines, lift needs, pictures/links…' rows={5}/></div><div className='md:col-span-2 flex items-center justify-between'><div className='text-xs text-slate-500'>By submitting, you agree to be contacted about your request.</div><Button type='submit' disabled={loading}>{loading?'Sending…':'Send Request'}</Button></div></form></CardContent></Card></div></section>
<footer className='bg-zinc-950 text-zinc-100'><div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12 grid md:grid-cols-4 gap-8'><div><div className='flex items-center gap-3'><Image src={logo} alt='Ruvison Technologies Logo' width={44} height={44} className='rounded-md bg-white p-1'/><div className='font-semibold'>Ruvison Technologies</div></div><div className='mt-3 text-sm text-zinc-300'>Reliable Networks & Trusted Security.</div></div><div><div className='font-semibold mb-2'>Services</div><ul className='space-y-1 text-sm text-zinc-300'><li>Computer Networking</li><li>Low‑Voltage Cabling</li><li>Security Cameras</li><li>Paging & Audio</li></ul></div><div><div className='font-semibold mb-2'>Contact</div><ul className='space-y-1 text-sm text-zinc-300'><li className='flex items-center gap-2'><PhoneCall className='h-4 w-4'/> (___) ___‑____</li><li className='flex items-center gap-2'><Mail className='h-4 w-4'/> info@ruvison.com</li><li className='flex items-center gap-2'><MapPin className='h-4 w-4'/> South Carolina, USA</li></ul></div><div><div className='font-semibold mb-2'>Resources</div><ul className='space-y-1 text-sm text-zinc-300'><li><a href='#work' className='hover:underline'>Case Studies</a></li><li><a href='#quote' className='hover:underline'>Request a Quote</a></li><li><a href='#about' className='hover:underline'>About Us</a></li></ul></div></div><div className='border-t border-white/10 py-4 text-center text-xs text-zinc-400'>© {new Date().getFullYear()} Ruvison Technologies LLC. All rights reserved.</div></footer>
</div>);}
function Testimonial({name,text}:{name:string;text:string}){return(<div className='rounded-xl border p-4 bg-white'><p className='text-slate-700'>“{text}”</p><div className='mt-2 text-xs text-slate-500'>— {name}</div></div>)}
